version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm --version
      - npm install -g npm@latest
      - npm --version
      - npm install
  pre_build:
    commands:
      - npm run lint
      #  - npm run test:ci
  build:
    commands:
      - npm run-script build

artifacts:
  base-directory: ./build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
