version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 14 # Workaround to actually install Node 14 on the CodeBuild instance
      - npm install
  build:
    commands:
      - npm run-script build

artifacts:
  base-directory: ./build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
